name: Linting
on: [push, pull_request]

jobs:
  lint:
    name: lint du code source
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: npm ci
      - name: Prettier
        run: npm run prettier
      - name: Lint
        run: npm run lint
